# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def sum_of_even_fib(upper_bound, fib1=1, fib2=2, fib_sum=2):
    next_fib = fib1 + fib2
    if next_fib < upper_bound:
        if next_fib % 2 == 0:
            fib_sum += next_fib
        return sum_of_even_fib(upper_bound, fib2, next_fib, fib_sum)
    else:
        return fib_sum

print(sum_of_even_fib(4000000))